version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    target-branch: "main"
    commit-message:
      prefix: "deps"
    labels:
      - "dependencies"
      - "security"
    reviewers:
      - "team-leads"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
    target-branch: "main"
    commit-message:
      prefix: "deps"
    labels:
      - "dependencies"
      - "security"
    reviewers:
      - "team-leads"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    labels:
      - "ci"
      - "security"
